I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 23, in script call
    call ch1_main
  File "game/script-ch1.rpy", line 36, in script
    p "Uh...hi, I'm [player]?"
Exception: Sayer 'p' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 23, in script call
    call ch1_main
  File "game/script-ch1.rpy", line 36, in script
    p "Uh...hi, I'm [player]?"
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'p' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Genshou Girls Festival 1.0
Tue Nov 22 04:03:17 2022
