I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script call
    call ch0_main
  File "game/script-ch0.rpy", line 76, in script
    p "Uh. Hi? Get out?"
Exception: Sayer 'p' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script call
    call ch0_main
  File "game/script-ch0.rpy", line 76, in script
    p "Uh. Hi? Get out?"
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'p' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Genshou Girls Festival 1.0
Sun Nov 13 23:38:23 2022
